tychedelia/kafka-protocol-rs

- README.md
- protocol_codegen/src/generate_messages.rs
- src/messages.rs
- src/messages/alter_partition_request.rs
- src/messages/alter_partition_response.rs
- src/messages/describe_log_dirs_response.rs
- src/messages/fetch_request.rs
- src/messages/leader_and_isr_request.rs
- src/messages/leader_and_isr_response.rs
- src/records.rs
Run gen command from the root path, instead of `cd` the sub directory to run it. This also prevent to generate a redundant `target` dir inside the `protocol_codegen` dir.
Fix the README file type to UNIX text file, BTW.
Further more, maybe we could specify a explicit release version or latest of the Kafka, to generate, by accepting a version tag of its repo.
> Run gen command from the root path

- protocol_codegen/src/generate_messages.rs
The generator fails to compute the destination path since std won't normalize "file.rs/../directory". This patch only removes the "file.rs" before normalization.
> Fix destination directory computation

- protocol_codegen/src/generate_messages.rs
- protocol_codegen/src/generate_messages/generate.rs
- protocol_codegen/src/generate_messages/spec.rs
I went through and applied all of clippy's warnings/errors to the protocol_codegen crate.
These all look non-controversial to me, except for one which I'll explain below.
Clippy does not like the use of `1..=0` because the range is in reverse and so will result in no values and after I investigated this line I agree with clippy's assessment.
`VersionSpec::range` is only called in one place which looks like this:
```rust
let range = valid_versions
.range()
.expect("Valid versions should be bounded.");
writeln!(
w,
"const VERSIONS: VersionRange = VersionRange {{ min: {}, max: {} }};",
range.start(),
range.end()
)?;
```
It doesnt use the range for iterating but instead just uses it to store a min and max.
`valid_versions` never contains a `VersionSpec::None` but if it did we would generate …
> apply clippy suggestions

- src/lib.rs
Indexmap is a dependency of this crate which is required in order to build many of the message types of this crate, making it part of the public API. As such, we re-export the crate so that users have immediate access to the code they need in order to use this crate meaningfully.
> Re-export indexmap

- src/protocol/buf.rs
This is useful as one of the primary pain points of working with the Kafka API is needing to manually encode the length delimiters. Often times it is nice to first reserve the necessary slot, continue to encode header & response body, then go back and fill the slot.
This pattern is used quite a lot internal to this crate. It is a useful pattern outside of this crate as well.
> Expose protocol::buf::gap module

- src/protocol/mod.rs
Fix some simple clippy lints, but also ignores another lint.
This ignored lint is unfortunate, wish I thought to test clippy before the release.
The `from_str` method should really be named `from_static_str`, but that will have to wait for 0.10
> Fix clippy lints

- src/compression/lz4.rs
kafka java client doesnt support depedent blocks. without the fix in this PR, the kafka java client will throw an exception.
https://github.com/a0x8o/kafka/blob/54eff6af115ee647f60129f2ce6a044cb17215d0/clients/src/main/java/org/apache/kafka/common/record/KafkaLZ4BlockOutputStream.java#L344
> fix lz4 compression

- protocol_codegen/src/generate_messages.rs
- src/compression/lz4.rs
- src/lib.rs
- src/messages.rs
This PR renames variant names as:
* `RequestKind::*Request` -> `RequestKind::*`
* `ResponseKind::*Response` -> `ResponseKind::*`
Repeating the same string in every variant name of an enum is generally considered bad practice, since that information should go in the type name instead. In this case the information is already in the type name so we can just drop it from the variant names.
Take for example this clippy lint, which would have triggered if it weren't for the fact that the type is part of the public API. Its disabled for public API's to prevent people from carelessly breaking their public API.
https://rust-lang.github.io/rust-clippy/master/index.html#/empty_enum_variants_with_brackets
This change is breaking and just a nice to have.
So it's probably best to avoid merging until we …
> [Breaking change] RequestKind/ResponseKind - Avoid redundant variant names

- Cargo.lock
- Cargo.toml
- tests/docker-compose.yaml
- tests/integration_tests.rs
This PR introduces a very basic integration test.
It uses the docker-compose-runner crate to spin up a kafka instance. This makes the test very easy to run both in CI and locally.
It then opens a socket to it and sends a single ApiVersions request, parses and response and does a few basic assertions on it.
At the moment it is essentially a smoke test. But it could be extended in the future to provide strong coverage across different APIs and versions.
I think this is a useful step towards being able to test the correctness of https://github.com/tychedelia/kafka-protocol-rs/pull/62
> Add basic integration test

- src/records.rs
For v0/v1 message sets, [Kafka uses `java.util.zip.CRC32`](https://github.com/apache/kafka/blob/a66a59f427b30611175fd029d86832d00aa5aabd/clients/src/main/java/org/apache/kafka/common/record/LegacyRecord.java#L29) which is `CRC_32_ISO_HDLC`, not `CRC_32_CKSUM`.
This will successfully decode message sets from Kafka v3.7. However, I have not yet tried to encode message sets and send them to Kafka.
> use CRC-32 ISO/HDLC instead of CRC-32 CKSUM

- src/records.rs
- tests/produce_fetch.rs
Just a small change to make the library slightly easier to use.
> Use `IntoIterator` instead of `Iterator` for `RecordBatchEncoder::encode`

- .github/workflows/build-and-test.yml
- Cargo.toml
- protocol_codegen/src/generate_messages.rs
- src/lib.rs
- src/messages.rs
This PR is a first step towards providing a higher level API for encoding and decoding messages.
Given the existence of the RequestKind and ResponseKind enums which has a variant for every possible request/response, it makes sense that the user would be matching on these enums and calling methods on the contained objects.
So this PR generates encode, decode and header_version methods on RequestKind/ResponseKind, to easily call into the contained object.
As an example, it will drastically simplify the implementation of the project I work on, which previously had these matches written out by hand:  https://github.com/shotover/shotover-proxy/pull/1736/files
I think that a further high level API can be written on top of this to simplify header/body encoding/decoding.
Also worth noting that …
> Add helper methods to RequestKind and ResponseKind

- Cargo.toml
- protocol_codegen/src/generate_messages.rs
- src/messages.rs
Thinking about it again I feel this name needs a plural since there are multiple enums enabled by the feature.
This is the last thing I want in before the new release.
> Rename messages_enum -> messages_enums

- CHANGELOG.md
- protocol_codegen/src/generate_messages.rs
- src/messages.rs
- src/messages/add_offsets_to_txn_request.rs
- src/messages/add_offsets_to_txn_response.rs
- src/messages/add_partitions_to_txn_request.rs
- src/messages/add_partitions_to_txn_response.rs
- src/messages/consumer_group_describe_request.rs
- src/messages/consumer_group_describe_response.rs
- src/messages/describe_topic_partitions_request.rs
- src/messages/describe_topic_partitions_response.rs
- src/messages/end_txn_request.rs
- src/messages/end_txn_response.rs
- src/messages/find_coordinator_request.rs
- src/messages/find_coordinator_response.rs
- src/messages/init_producer_id_request.rs
- src/messages/init_producer_id_response.rs
- src/messages/k_raft_version_record.rs
- src/messages/list_client_metrics_resources_response.rs
- src/messages/list_groups_request.rs
- src/messages/list_groups_response.rs
- src/messages/list_transactions_request.rs
- src/messages/list_transactions_response.rs
- src/messages/metadata_response.rs
- src/messages/produce_request.rs
- src/messages/produce_response.rs
- src/messages/txn_offset_commit_request.rs
- src/messages/txn_offset_commit_response.rs
- src/messages/voters_record.rs
closes https://github.com/tychedelia/kafka-protocol-rs/issues/74
This PR is a breaking change since `#[non-exhaustive]` is not used everywhere.
> Update to kafka 3.8

- CHANGELOG.md
- protocol_codegen/src/generate_messages.rs
- src/messages.rs
kafka-protocol has generated newtypes, which wrap integers and strings to give some extra type safety.
For example:
* BrokerId wraps i32
* GroupId wraps StrBytes
Currently the Debug impl for these types is derived by `#[derive(Debug)]`.
This results in debug output like:
* BrokerId(2)
* GroupId("some group")
This PR changes the debug output to instead directly display the type:
* 2
* "some group"
This should result in more concise logs.
Here are some example usages:
```rust
tracing::info!("Received request for group {group_id:?}");
// before
// Received request for group GroupId("foo")
// after
// Received request for group "foo"
//
// assuming the user specifies that its a group the log is easier to read
tracing::info!("{fetch_request:?}");
// before
//Fetch(FetchRequest { cluster_id: …
```
> Make Debug impl for newtypes passthrough to inner type

- protocol_codegen/src/generate_messages.rs
- protocol_codegen/src/main.rs
This PR has two changes:
1. non-codegen related logic is moved out of `generate_messages.rs` and into `main.rs`
+ this ensures the logic in this function better matches the name and is entirely focused on code gen.
+ it also reduces the scope of this function reducing the negative impact of the second change.
2. `module_file` variable is renamed to `m`.
+ while I normally detest single letter variable names, in this case making it small reduces line length enough for rust format to reduce many multi-line statements into a single line, resulting in a line count reduction of 53 lines.
+ its also pretty clear what it does since the whole function revolves around writing to it.
There are no functional changes, code is only moved or renamed.
> Cleanup generate messages

- .github/workflows/build-and-test.yml
Should help alleviate the CI runtime cost of https://github.com/tychedelia/kafka-protocol-rs/pull/86 a little.
I tested without the `save-if` in order to test caching before this PR is merged, and it looks this PR saves ~30s in CI time.
> Cache CI builds

- Cargo.toml
- src/compression.rs
- src/compression/lz4.rs
- src/records.rs
This PR moves support for each record compression type into its own cargo feature.
This will improve build times for projects that:
* do not use the kafka-protocol crate's record types
* specialized clients that only need to work with a subset of the compression types
* clients that implement their compression logic.
By default all of these new features are enabled since a regular client or broker would want to support all of them.
If a compression feature is not enabled it is up to the client or broker implementation to communicate that to the other side at the protocol level to avoid hitting the `"support for {c:?} is not enabled as a cargo feature"` error.
One downside is this has increased our CI runtime from 2 mins to 17 mins.
But I think this is tolerable and worth it.
In the …
> make record compression into default features

- Cargo.toml
- rust-toolchain.toml
- src/protocol/mod.rs
- src/protocol/types.rs
- src/records.rs
Update the pinned rust version and fix clippy lints.
Turns out the feature for snappy compression was broken, the name of the feature was different to the name used in the `cfg`s and rust 1.76 didnt pick this up yet.
I set the feature name to ["snappy"](https://google.github.io/snappy/) to match the name of the compression format rather than the name ["snap"](https://github.com/BurntSushi/rust-snappy) which is the rust crate that implements snappy, since the choice of crate is an implementation detail.
AFAIK this project has no MSRV requirements, so the toolchain is not set to an old version to ensure an MSRV, if desired I can leave it a few versions behind though.
> update pinned rust + fix clippy lints

- src/protocol/types.rs
This PR alters the decode logic for maps to avoid reallocations due to map growth from insertions.
By using iterators + collect the size of the allocation required for the IndexMap is known up front, avoiding the need for reallocations as decoded items are inserted to the map.
This should give a small speed up to decoding of produce messages since they use maps.
> Reduce allocations when decoding maps

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Releases kafka-protocol 0.13
@tychedelia up to you if you want to include https://github.com/tychedelia/kafka-protocol-rs/pull/90 in this release, I've done a full writeup on my thoughts in the PR.
> Release 0.13

- src/records.rs
- tests/all_tests/fetch_response.rs
- tests/all_tests/produce_fetch.rs
Calling encode or decode with the correct compression automatically chosen is very difficult. Providing None results in an error like this:
```
1  error[E0283]: type annotations needed
--> kafka-fetch-rewrite/src/lib.rs:87:88
|
87  | ...                   RecordBatchDecoder::decode(&mut records_bytes.clone(), None)
|                       --------------------------                             ^^^^ cannot infer type of the type parameter `T` declared on the enum `Option`
|                       |
|                       required by a bound introduced by this call
|
= note: multiple `impl`s satisfying `for<'a> _: Fn(&'a mut bytes::Bytes, kafka_protocol::records::Compression)` found in the following crates: `alloc`, `core`:
- impl<A, F> std::ops::Fn<A> for &F
where A: std::marker::Tuple, F: …
```
> [Breaking change] Fix calling `Records::encode` / `Records::decode` with None

- README.md
- protocol_codegen/src/generate_messages.rs
- src/lib.rs
- src/messages.rs
- tests/all_tests/integration_tests.rs
- tests/all_tests/produce_fetch.rs
Similar change to https://github.com/tychedelia/kafka-protocol-rs/pull/61
The "Key" suffix is redundant since the variants are usually written out as `ApiKey::ProduceKey`.
Additionally its common to log a key type by doing something like `log!("failed to parse message type {api_key:?}")`, in this case including the Key is confusing because it seems like `Key` is part of the message name.
> [Breaking change] remove "Key" suffix from ApiKey variants

- src/protocol/mod.rs
This PR introduces 2 new pieces of functionality around VersionRange.
These were required to implement a unit test in my project that compares the currently supported versions of the project against the supported versions of the kafka-protocol crate.
The additions are:
* Add PartialEq impl for VersionRange
+ allows for direct comparison between ranges which seems like a reasonable operation.
* Add Display impl for VersionRange
+ It takes the format `0..10` where min is 0 and max is 10
+ This compact format will be nice for logs and error messages.
+ Possibly we should do `0 to 10` or `0-10` or `0..=10` instead, since in regular rust `0..10` would mean an exclusive 10.
> VersionRange additions

- CHANGELOG.md
- src/records.rs
- tests/all_tests/fetch_response.rs
- tests/all_tests/produce_fetch.rs
Wow, I really messed this one up. Sorry everyone.
In https://github.com/tychedelia/kafka-protocol-rs/pull/100 I left the trait bounds in which completely failed to address the actual issue of making the function difficult to call, while also making it more confusing (what are the trait bounds for??)
This PR fixes the issue.
I've also adjusted some of the unit tests, to verify that I have actually resolved the issue, which I should have done in the first place
> [Breaking Change] Remove unneeded trait bounds from Records::encode/Records::decode

- src/protocol/types.rs
> #107 Explicitly use trait impl in types

- Cargo.lock
- Cargo.toml
closes https://github.com/tychedelia/kafka-protocol-rs/issues/107
The latest release of kafka-protocol (v0.14.0) no longer builds with the latest minor release of bytes (v1.10.0)
What I've done to fix this:
1. I have setup a V0.14.0 branch from the 0.14.0 bump commit.
2. Then I merged https://github.com/tychedelia/kafka-protocol-rs/pull/109 to the V0.14.0 branch
3. This PR adds a V0.14.1 version bump to the V0.14.0 branch
@tychedelia I would appreciate a review + merge + `cargo publish` for the `V0.14.0` branch (not the `main` branch)
> Release V0.14.1

- README.md
- protocol_codegen/src/main.rs
- src/messages.rs
- src/messages/add_raft_voter_request.rs
- src/messages/add_raft_voter_response.rs
- src/messages/api_versions_request.rs
- src/messages/api_versions_response.rs
- src/messages/begin_quorum_epoch_request.rs
- src/messages/begin_quorum_epoch_response.rs
- src/messages/broker_registration_request.rs
- src/messages/create_topics_request.rs
- src/messages/describe_quorum_request.rs
- src/messages/describe_quorum_response.rs
- src/messages/end_quorum_epoch_request.rs
- src/messages/end_quorum_epoch_response.rs
- src/messages/fetch_request.rs
- src/messages/fetch_response.rs
- src/messages/fetch_snapshot_request.rs
- src/messages/fetch_snapshot_response.rs
- src/messages/find_coordinator_request.rs
- src/messages/find_coordinator_response.rs
- src/messages/list_offsets_request.rs
- src/messages/list_offsets_response.rs
- src/messages/remove_raft_voter_request.rs
- src/messages/remove_raft_voter_response.rs
- src/messages/update_raft_voter_request.rs
- src/messages/update_raft_voter_response.rs
- src/messages/vote_response.rs
In theory this should be a non-breaking change, we already have a breaking change merged though, so no worries if its not.
> Update messages to kafka 3.9

- src/protocol/mod.rs
- src/records.rs
The [condition on equivalent Hash implementations for implementing Borrow](https://doc.rust-lang.org/std/borrow/trait.Borrow.html#examples) is not satisfied for `&str` and `StrBytes` but it is for `&[u8]` and `StrBytes`.
It failed to work when using the crate and the Hash implementations `StrBytes`/`str` do indeed give different results unlike `StrBytes`/`[u8]` so why did the test work?
[Looking at the implementation of `IndexMap::get`](https://docs.rs/indexmap/latest/src/indexmap/map.rs.html#759-765) shows us that the lookup key is only hashed if the map has more than one entry.
`Borrow` is tricky indeed :smile: 
See #115
> fix: `impl Borrow<[u8]> for StrBytes`, not `Borrow<str>`

- src/records.rs
- tests/all_tests/fetch_response.rs
- tests/all_tests/produce_fetch.rs
This doesn't support getting compression for record encoding v0/v1 aka message sets.
Closes https://github.com/tychedelia/kafka-protocol-rs/issues/116
> feat: return compression information when decoding if possible

- CHANGELOG.md
- Cargo.lock
- src/protocol/buf.rs
- src/protocol/types.rs
closes https://github.com/tychedelia/kafka-protocol-rs/issues/111
Small cleanup now that we know for sure that the `bytes` project will retain these methods.
> Remove ByteBuf try_get_ methods [breaking change]

- Cargo.lock
- Cargo.toml
We should make a final release before moving to kafka 4.0 as we will need to remove support for message sets v0/v1 which could be disruptive. See https://github.com/tychedelia/kafka-protocol-rs/pull/120#issuecomment-2833757686
Also we should merge these PRs before this release:
* https://github.com/tychedelia/kafka-protocol-rs/pull/121
* https://github.com/tychedelia/kafka-protocol-rs/pull/123
I will give @tychedelia a few days to review the prereq PRs and then I will merge them, followed by this PR.
> Release kafka-protocol 0.15.0

- Cargo.toml
Introduced in #121
The `Buf::try_get_*` methods in `bytes` are provided since [1.10.0](https://github.com/tokio-rs/bytes/blob/master/CHANGELOG.md#1100-february-3rd-2025).
The `0.15.0` release should be yanked.
BTW, the commit of `0.15.0` tag ([`54af533`](https://github.com/tychedelia/kafka-protocol-rs/commit/54af5331404684ff82bef660fd094e402db27bb7)) 
> does not belong to any branch on this repository, and may belong to a fork outside of the repository.
> Fix bytes version

- src/error.rs
Kafka error codes/types should be updated with the Kafka version support updated.
The current error codes are at Kafka version 3.2.0 when they first added. I add new error codes from 3.3.0 to 4.1.0(rc1). It's ok that the error codes are newer than the supported message version 3.9.0 (#105).
> Update Kafka error codes to 4.1.0
